src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;


#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $ville = null;

    #[ORM\Column]
    private ?int $telephone = null;

    #[ORM\Column(length: 255)]
    private ?string $methode_paiement = null;

    #[ORM\Column(type: Types::BLOB)]
    private $article = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getTelephone(): ?int
    {
        return $this->telephone;
    }

    public function setTelephone(int $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getMethodePaiement(): ?string
    {
        return $this->methode_paiement;
    }

    public function setMethodePaiement(string $methode_paiement): self
    {
        $this->methode_paiement = $methode_paiement;

        return $this;
    }

    public function getArticle()
    {
        return $this->article;
    }

    public function setArticle($article): self
    {
        $this->article = $article;

        return $this;
    }
}

src/Form/CommandeType.php
<?php

namespace App\Form;

use App\Entity\Commande;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextType;




class CommandeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class, [
                'label' => 'First Name  '
            ])
            ->add('prenom', TextType::class, [
                'label' => 'last Name  '
            ])
            ->add('ville', TextType::class, [
                'label' => 'city  '
            ])
            ->add('telephone')
            ->add('telephone', TelType::class, [
                'label' => 'phone '
            ])
            ->add('methode_paiement', ChoiceType::class, [
                'label' => 'method',
                'choices' => [
                    'Cash' => 'Cash',
                    'Debit cards' => 'Debit cards',
                    'Credit cards' => 'Credit cards',
                ]
            ])
            ->add('article')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Commande::class,
        ]);
    }
}

src/Controller/CommandeController.php
<?php

namespace App\Controller;

use App\Entity\Commande;
use App\Form\CommandeType;
use App\Repository\CommandeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/commande')]
class CommandeController extends AbstractController
{
    #[Route('/', name: 'app_commande_index', methods: ['GET'])]
    public function index(CommandeRepository $commandeRepository): Response
    {
        return $this->render('commande/index.html.twig', [
            'commandes' => $commandeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_commande_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CommandeRepository $commandeRepository): Response
    {
        $commande = new Commande();
        $form = $this->createForm(CommandeType::class, $commande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $commandeRepository->save($commande, true);

            return $this->redirectToRoute('app_commande_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('commande/new.html.twig', [
            'commande' => $commande,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_commande_show', methods: ['GET'])]
    public function show(Commande $commande): Response
    {
        return $this->render('commande/show.html.twig', [
            'commande' => $commande,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_commande_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Commande $commande, CommandeRepository $commandeRepository): Response
    {
        $form = $this->createForm(CommandeType::class, $commande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $commandeRepository->save($commande, true);

            return $this->redirectToRoute('app_commande_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('commande/edit.html.twig', [
            'commande' => $commande,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_commande_delete', methods: ['POST'])]
    public function delete(Request $request, Commande $commande, CommandeRepository $commandeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commande->getId(), $request->request->get('_token'))) {
            $commandeRepository->remove($commande, true);
        }

        return $this->redirectToRoute('app_commande_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/commande/_delete_form.html.twig
<form method="post" action="{{ path('app_commande_delete', {'id': commande.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commande.id) }}">
 <center>   <button class="btn">Delete</button> </center>
</form>

templates/commande/_form.html.twig
<div class="for">
{{ form_start(form) }}
    {{ form_widget(form) }}
   <center> <button class="btn">{{ button_label|default('Order') }}</button></center>
{{ form_end(form) }} </div>
<style>
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  -webkit-font-smoothing: antialiased;
  -moz-font-smoothing: antialiased;
  -o-font-smoothing: antialiased;
 
  text-rendering: optimizeLegibility;
}
.for {
     display: flex;
  flex-direction: column;
 
 
        background-color: #add7df;
      
			padding: 50px;
			border-radius: 80px;
			margin: 50px auto;
			width: 60%;
			box-shadow: 0 0 10px rgba(10, 1, 1, 0.5);
            
            position: absolute;
             top: 150px;
             left: 50%;
              transform: translateX(-50%);

}
.btn{
 
  background-color: #007bff;
  color: #fff;
  border: none;
  border-radius: 3px;
  cursor: pointer;
}

label {
  display: block;
  margin-bottom: 10px;
   font-weight: bold;
}

input {
  display: block;
  width: 100%;
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 3px;
}

</style>

templates/commande/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Commande{% endblock %}

{% block body %}
    <h1>Edit Commande</h1>

    {{ include('commande/_form.html.twig', {'button_label': 'Update'}) }}



    {{ include('commande/_delete_form.html.twig') }}
{% endblock %}

templates/commande/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande index{% endblock %}

{% block body %}
    <h1>Commande index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Ville</th>
                <th>Telephone</th>
                <th>Methode_paiement</th>
                <th>Article</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commande in commandes %}
            <tr>
                <td>{{ commande.id }}</td>
                <td>{{ commande.nom }}</td>
                <td>{{ commande.prenom }}</td>
                <td>{{ commande.ville }}</td>
                <td>{{ commande.telephone }}</td>
                <td>{{ commande.methodePaiement }}</td>
                <td>{{ commande.article }}</td>
                <td>
                    <a href="{{ path('app_commande_show', {'id': commande.id}) }}">show</a>
                    <a href="{{ path('app_commande_edit', {'id': commande.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_commande_new') }}">Create new</a>
{% endblock %}

templates/commande/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Commande{% endblock %}

{% block body %}
    <center > <h1>Create new Commande</h1> </center> 

    {{ include('commande/_form.html.twig') }}

   
{% endblock %}

templates/commande/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande{% endblock %}

{% block body %}
    <center > <h1>Commande</h1> </center> 

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commande.id }}</td>
                <td> </td> 
            </tr>
            <tr> </tr> 
            <tr>
                <th>Nom</th>
                <td>{{ commande.nom }}</td>
                 <td> </td> 
            </tr>
            <tr> </tr> 
            <tr>
                <th>Prenom</th>
                <td>{{ commande.prenom }}</td>
                 <td> </td> 
            </tr>
            <tr> </tr> 
            <tr>
                <th>Ville</th>
                <td>{{ commande.ville }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ commande.telephone }}</td>
            </tr>
            <tr>
                <th>Methode_paiement</th>
                <td>{{ commande.methodePaiement }}</td>
            </tr>
            <tr>
                <th>Article</th>
                <td>{{ commande.article }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_commande_index') }}">back to list</a>

    <a href="{{ path('app_commande_edit', {'id': commande.id}) }}">edit</a>

    {{ include('commande/_delete_form.html.twig') }}
{% endblock %}