src/Entity/Inscription.php
<?php

namespace App\Entity;

use App\Repository\InscriptionRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: InscriptionRepository::class)]
class Inscription
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;
    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_naissance = null;

    #[ORM\Column(length: 255)]
    private ?string $adress = null;

    #[ORM\Column]
    private ?int $code_postal = null;

    #[ORM\Column]
    private ?int $telephone = null;

    #[ORM\Column(length: 255)]
    private ?string $mail = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_depart = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_arrive = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->code_postal;
    }

    public function setCodePostal(int $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getTelephone(): ?int
    {
        return $this->telephone;
    }

    public function setTelephone(int $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getDateDepart(): ?\DateTimeInterface
    {
        return $this->date_depart;
    }

    public function setDateDepart(\DateTimeInterface $date_depart): self
    {
        $this->date_depart = $date_depart;

        return $this;
    }

    public function getDateArrive(): ?\DateTimeInterface
    {
        return $this->date_arrive;
    }

    public function setDateArrive(\DateTimeInterface $date_arrive): self
    {
        $this->date_arrive = $date_arrive;

        return $this;
    }
}

src/Form/InscriptionType.php
<?php

namespace App\Form;

use App\Entity\Inscription;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextType;





class InscriptionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
       
        ->add('nom', TextType::class, [
            'label' => 'First Name  '
        ])
        ->add('prenom', TextType::class, [
            'label' => 'last Name  '
        ])

            ->add('date_naissance')
            ->add('adress', TextType::class, [
                'label' => 'address   '
            ])
            ->add('code_postal')
            ->add('telephone', TelType::class, [
                'label' => 'phone'
            ])
            ->add('mail', EmailType::class, [
                'label' => ' mail'
            ])
            ->add('date_depart')
            ->add('date_arrive')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Inscription::class,
        ]);
    }
}

src/Controller/InscriptionController.php
<?php

namespace App\Controller;

use App\Entity\Inscription;
use App\Form\InscriptionType;
use App\Repository\InscriptionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/inscription')]
class InscriptionController extends AbstractController
{
    #[Route('/', name: 'app_inscription_index', methods: ['GET'])]
    public function index(InscriptionRepository $inscriptionRepository): Response
    {
        return $this->render('inscription/index.html.twig', [
            'inscriptions' => $inscriptionRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_inscription_new', methods: ['GET', 'POST'])]
    public function new(Request $request, InscriptionRepository $inscriptionRepository): Response
    {
        $inscription = new Inscription();
        $form = $this->createForm(InscriptionType::class, $inscription);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $inscriptionRepository->save($inscription, true);

            return $this->redirectToRoute('app_inscription_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('inscription/new.html.twig', [
            'inscription' => $inscription,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_inscription_show', methods: ['GET'])]
    public function show(Inscription $inscription): Response
    {
        return $this->render('inscription/show.html.twig', [
            'inscription' => $inscription,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_inscription_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Inscription $inscription, InscriptionRepository $inscriptionRepository): Response
    {
        $form = $this->createForm(InscriptionType::class, $inscription);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $inscriptionRepository->save($inscription, true);

            return $this->redirectToRoute('app_inscription_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('inscription/edit.html.twig', [
            'inscription' => $inscription,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_inscription_delete', methods: ['POST'])]
    public function delete(Request $request, Inscription $inscription, InscriptionRepository $inscriptionRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$inscription->getId(), $request->request->get('_token'))) {
            $inscriptionRepository->remove($inscription, true);
        }

        return $this->redirectToRoute('app_inscription_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/inscription/_delete_form.html.twig
<form method="post" action="{{ path('app_inscription_delete', {'id': inscription.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ inscription.id) }}">
 <center >   <button class="btn">Delete</button> </center>
</form>

templates/inscription/_form.html.twig
<div class ="for">
{{ form_start(form) }}
    {{ form_widget(form) }}
  <center>  <button class="btn">{{ button_label|default('Envoyer') }}</button> </center>
{{ form_end(form) }}
<style>
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  -webkit-font-smoothing: antialiased;
  -moz-font-smoothing: antialiased;
  -o-font-smoothing: antialiased;
 
  text-rendering: optimizeLegibility;
}
.for {
     display: flex;
  flex-direction: column;
 
 
        background-color: #add7df;
      
			padding: 50px;
			border-radius: 80px;
			margin: 50px auto;
			width: 60%;
			box-shadow: 0 0 10px rgba(10, 1, 1, 0.5);
            
            position: absolute;
             top: 150px;
             left: 50%;
              transform: translateX(-50%);

}
.btn{
 
  background-color: #007bff;
  color: #fff;
  border: none;
  border-radius: 3px;
  cursor: pointer;
}

label {
  display: block;
  margin-bottom: 10px;
   font-weight: bold;
}

input {
  display: block;
  width: 100%;
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 3px;
}

</style>

templates/inscription/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Inscription{% endblock %}

{% block body %}
    <h1>Edit Inscription</h1>

  {#  {{ include('inscription/_form.html.twig', {'button_label': 'Update'}) }}  #}

   {# <a href="{{ path('app_inscription_index') }}">back to list</a> #}

    {{ include('inscription/_delete_form.html.twig') }}
{% endblock %}

templates/inscription/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscription index{% endblock %}

{% block body %}
    <h1>Inscription index</h1>
    <style>
    .table {
      background-color:D18113;
    }
    </style>

    <table class="table" >
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Date_naissance</th>
                <th>Adress</th>
                <th>Code_postal</th>
                <th>Telephone</th>
                <th>Mail</th>
                <th>Date_depart</th>
                <th>Date_arrive</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for inscription in inscriptions %}
            <tr>
                <td>{{ inscription.id }}</td>
                <td>{{ inscription.nom }}</td>
                <td>{{ inscription.prenom }}</td>
                <td>{{ inscription.dateNaissance ? inscription.dateNaissance|date('Y-m-d') : '' }}</td>
                <td>{{ inscription.adress }}</td>
                <td>{{ inscription.codePostal }}</td>
                <td>{{ inscription.telephone }}</td>
                <td>{{ inscription.mail }}</td>
                <td>{{ inscription.dateDepart ? inscription.dateDepart|date('Y-m-d') : '' }}</td>
                <td>{{ inscription.dateArrive ? inscription.dateArrive|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_inscription_show', {'id': inscription.id}) }}">show</a>
                    <a href="{{ path('app_inscription_edit', {'id': inscription.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_inscription_new') }}">Create new</a>
{% endblock %}

templates/inscription/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Inscription{% endblock %}

{% block body %}
   <center >  <h1>Create new Inscription</h1> </center > 

    {{ include('inscription/_form.html.twig') }}

  {#  <a href="{{ path('app_inscription_index') }}">back to list</a> #}
{% endblock %}

templates/inscription/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscription{% endblock %}

{% block body %}
   <center >  <h1>Inscription</h1> </center> 

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ inscription.id }}</td>
            </tr>
            <tr>
                <th>Nom</th> 
                <td>{{ inscription.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th> 
                <td>{{ inscription.prenom }}</td>
            </tr>
            <tr>
                <th>Date_naissance</th>
                <td>{{ inscription.dateNaissance ? inscription.dateNaissance|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Adress</th>
                <td>{{ inscription.adress }}</td>
            </tr>
            <tr>
                <th>Code_postal</th>
                <td>{{ inscription.codePostal }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ inscription.telephone }}</td>
            </tr>
            <tr>
                <th>Mail</th>
                <td>{{ inscription.mail }}</td>
            </tr>
            <tr>
                <th>Date_depart</th>
                <td>{{ inscription.dateDepart ? inscription.dateDepart|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_arrive</th>
                <td>{{ inscription.dateArrive ? inscription.dateArrive|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

  {#  <a href="{{ path('app_inscription_index') }}">back to list</a> #}

    <a href="{{ path('app_inscription_edit', {'id': inscription.id}) }}">edit</a>

    {{ include('inscription/_delete_form.html.twig') }}
{% endblock %}